#
# Copyright (C) 2016 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

#USE_NINJA := false
BUILD_DATE := $(shell date -u +"%s")
DEVICE_PATH := device/ulefone/t1
MTK_PROJECT_CONFIG := $(DEVICE_PATH)/ProjectConfig.mk
PRODUCT_SYSTEM_DEFAULT_PROPERTIES := \
  dalvik.vm.image-dex2oat-Xms=64m \
  dalvik.vm.image-dex2oat-Xmx=384m \
  dalvik.vm.dex2oat-Xms=64m \
  dalvik.vm.dex2oat-Xmx=512m \
  pm.dexopt.first-boot=interpret-only \
  pm.dexopt.boot=verify-profile \
  pm.dexopt.install=interpret-only \
  pm.dexopt.ab-ota=speed-profile \
  pm.dexopt.bg-dexopt=speed-profile \
  pm.dexopt.nsys-library=speed \
  pm.dexopt.forced-dexopt=speed \
  pm.dexopt.shared-apk=speed \
  pm.dexopt.core-app=speed \
  ro.build.selinux=0 \
  ro.build.selinux.enforce=0 \
  ro.boot.selinux=permissive \
  ro.secure=0 \
  ro.debuggable=1 \
  ro.adb.secure=0 \
  persist.service.adb.enable=1 \
  persist.service.debuggable=1 \
  persist.sys.usb.config=mtp,adb \
  persist.sys.root_access=1 \
  ro.sys.usb.configfs=1 \
  ro.oem_unlock_supported=1 \
  security.perf_harden=0 \
  ro.allow.mock.location=1 \
  ro.debuggable=1 \
  ro.telephony.ril.config=fakeiccid \
  dalvik.vm.usejit=true \
  dalvik.vm.usejitprofiles=true \
  dalvik.vm.appimageformat=lz4 \
  ro.mount.fs=EXT4 \
  camera.disable_zsl_mode=1 \
  ro.dalvik.vm.native.bridge=0

# Project & Platform settings
include $(DEVICE_PATH)/PlatformConfig.mk
include $(DEVICE_PATH)/board/mt6757.mk
include $(MTK_PROJECT_CONFIG)
MTK_INTERNAL_CDEFS := $(foreach t,$(AUTO_ADD_GLOBAL_DEFINE_BY_NAME),$(if $(filter-out no NO none NONE false FALSE,$($(t))),-D$(t)))
MTK_INTERNAL_CDEFS += $(foreach t,$(AUTO_ADD_GLOBAL_DEFINE_BY_VALUE),$(if $(filter-out no NO none NONE false FALSE,$($(t))),$(foreach v,$(shell echo $($(t)) | tr '[a-z]' '[A-Z]'),-D$(v))))
MTK_INTERNAL_CDEFS += $(foreach t,$(AUTO_ADD_GLOBAL_DEFINE_BY_NAME_VALUE),$(if $(filter-out no NO none NONE false FALSE,$($(t))),-D$(t)=\"$($(t))\"))
BOARD_GLOBAL_CFLAGS += $(MTK_INTERNAL_CDEFS)
BOARD_GLOBAL_CPPFLAGS += $(MTK_INTERNAL_CDEFS)
BOARD_GLOBAL_CPPFLAGS += -DMTK_HARDWARE
BOARD_GLOBAL_CFLAGS += \
  -DMTK_HARDWARE \
  -DCOMPAT_SENSORS_M \
  -DNO_SECURE_DISCARD \
  -DDISABLE_HW_ID_MATCH_CHECK
LOCAL_LDLIBS := -lGLESv3
#LINKER_FORCED_SHIM_LIBS := $(LINKER_FORCED_SHIM_LIBS):/system/

# Addidional platform options
#BOARD_EGL_WORKAROUND_BUG_10194508 := true
#BOARD_USES_LEGACY_MTK_AV_BLOB := true
#TARGET_HAS_LEGACY_CAMERA_HAL1 := true
#BOARD_CHARGER_DISABLE_INIT_BLANK := true
BOARD_USES_ALSA_AUDIO := true
BOARD_EGL_NEEDS_HANDLE_VALUE := true
BOARD_PROVIDES_RILD := true
BLOCK_BASED_OTA := false
BOARD_EGL_NEEDS_FNW := true
BOARD_HAS_MTK_HARDWARE := true
BOARD_USES_MTK_HARDWARE := true
BOARD_HAS_FLIPPED_SCREEN := true
BOARD_EGL_CFG := $(DEVICE_PATH)/configs/egl.cfg

#EXTENDED_FONT_FOOTPRINT := true
#DONT_DEXPREOPT_PRBUILTS := true
WITH_DEXPREOPT_PIC := true
CONFIG_NR_CPUS := 8
MTK_MMPROFILE_SUPPORT := true
MTK_FM_RX_SUPPORT := yes
WITH_DEXPREOPT := true
FM_LIB_BUILD_MT6625 := yes
USE_XML_AUDIO_POLICY_CONF := 1
USE_CUSTOM_AUDIO_POLICY := 1
MTK_HARDWARE := true
MTK_FM_SUPPORT := yes

#TARGET_USERIMAGES_SPARSE_EXT_DISABLED := false
#TARGET_PROVIDES_INIT_RC := true
#TARGET_INCLUDE_XLOG_SYMBOLS := true
#TARGET_INCLUDE_AUDIO_SYMBOLS := true
#TARGET_INCLUDE_OMX_SYMBOLS := true
#TARGET_INCLUDE_GUI_SYMBOLS := true
#TARGET_INCLUDE_UI_SYMBOLS := true
#TARGET_INCLUDE_CAMERA_SYMBOLS := true
#TARGET_INCLUDE_GPS_SYMBOLS := true
TARGET_CPU_MEMCPY_OPT_DISABLE := true
TARGET_TEE_IS_OPTEE := true
TARGET_KEYMASTER_WAIT_FOR_QSEE := true
TARGET_PROVIDES_KEYMASTER := true
TARGET_RUNNING_WITHOUT_SYNC_FRAMEWORK := true
TARGET_REQUIRES_SYNCHRONOUS_SETSURFACE := true
TARGET_NEEDS_PLATFORM_TEXT_RELOCATIONS := true
TARGET_OTA_ASSERT_DEVICE := t1,p15v57c2k_gq_tee,,
TARGET_KMODULES := true
TARGET_SPECIFIC_HEADER_PATH := $(LOCAL_PATH)/include
TARGET_SYSTEM_PROP := $(DEVICE_PATH)/system.prop

PRODUCT_DEFAULT_PROPERTY_OVERRIDES := \
  dalvik.vm.image-dex2oat-Xms=64m \
  dalvik.vm.image-dex2oat-Xmx=384m \
  dalvik.vm.dex2oat-Xms=64m \
  dalvik.vm.dex2oat-Xmx=512m \
  pm.dexopt.first-boot=interpret-only \
  pm.dexopt.boot=verify-profile \
  pm.dexopt.install=interpret-only \
  pm.dexopt.ab-ota=speed-profile \
  pm.dexopt.bg-dexopt=speed-profile \
  pm.dexopt.nsys-library=speed \
  pm.dexopt.forced-dexopt=speed \
  pm.dexopt.shared-apk=speed \
  pm.dexopt.core-app=speed \
  ro.secure=0 \
  ro.debuggable=1 \
  ro.adb.secure=0 \
  persist.service.adb.enable=1 \
  persist.service.debuggable=1 \
  persist.sys.usb.config=mtp,adb \
  persist.sys.root_access=1 \
  ro.sys.usb.configfs=1 \
  ro.oem_unlock_supported=1 \
  security.perf_harden=0 \
  ro.allow.mock.location=1 \
  ro.debuggable=1 \
  ro.telephony.ril.config=fakeiccid \
  dalvik.vm.usejit=true \
  dalvik.vm.usejitprofiles=true \
  dalvik.vm.appimageformat=lz4 \
  ro.mount.fs=EXT4 \
  camera.disable_zsl_mode=1 \
  ro.dalvik.vm.native.bridge=0

PRODUCT_PROPERTY_OVERRIDES := \
  dalvik.vm.image-dex2oat-Xms=64m \
  dalvik.vm.image-dex2oat-Xmx=64m \
  dalvik.vm.dex2oat-Xms=64m \
  dalvik.vm.dex2oat-Xmx=512m \
  pm.dexopt.first-boot=interpret-only \
  pm.dexopt.boot=verify-profile \
  pm.dexopt.install=interpret-only \
  pm.dexopt.ab-ota=speed-profile \
  pm.dexopt.bg-dexopt=speed-profile \
  pm.dexopt.nsys-library=speed \
  pm.dexopt.forced-dexopt=speed \
  pm.dexopt.shared-apk=speed \
  pm.dexopt.core-app=speed \
  ro.build.selinux=0 \
  ro.build.selinux.enforce=0 \
  ro.boot.selinux=permissive \
  ro.secure=0 \
  ro.debuggable=1 \
  ro.adb.secure=0 \
  persist.service.adb.enable=1 \
  persist.service.debuggable=1 \
  persist.sys.usb.config=mtp,adb \
  persist.sys.root_access=1 \
  ro.sys.usb.configfs=1 \
  ro.oem_unlock_supported=1 \
  security.perf_harden=0 \
  ro.allow.mock.location=1 \
  ro.debuggable=1 \
  ro.telephony.ril.config=fakeiccid \
  dalvik.vm.usejit=true \
  dalvik.vm.usejitprofiles=true \
  dalvik.vm.appimageformat=lz4 \
  ro.mount.fs=EXT4 \
  camera.disable_zsl_mode=1 \
  ro.dalvik.vm.native.bridge=0

ADDITIONAL_DEFAULT_PROPERTIES := \
  dalvik.vm.image-dex2oat-Xms=64m \
  dalvik.vm.image-dex2oat-Xmx=384m \
  dalvik.vm.dex2oat-Xms=64m \
  dalvik.vm.dex2oat-Xmx=512m \
  pm.dexopt.first-boot=interpret-only \
  pm.dexopt.boot=verify-profile \
  pm.dexopt.install=interpret-only \
  pm.dexopt.ab-ota=speed-profile \
  pm.dexopt.bg-dexopt=speed-profile \
  pm.dexopt.nsys-library=speed \
  pm.dexopt.forced-dexopt=speed \
  pm.dexopt.shared-apk=speed \
  pm.dexopt.core-app=speed \
  ro.build.selinux=0 \
  ro.build.selinux.enforce=0 \
  ro.boot.selinux=permissive \
  ro.secure=0 \
  ro.debuggable=1 \
  ro.adb.secure=0 \
  persist.service.adb.enable=1 \
  persist.service.debuggable=1 \
  persist.sys.usb.config=mtp,adb \
  persist.sys.root_access=1 \
  ro.sys.usb.configfs=1 \
  ro.oem_unlock_supported=1 \
  security.perf_harden=0 \
  ro.allow.mock.location=1 \
  ro.debuggable=1 \
  ro.zygote=zygote64_32 \
  ro.kernel.android.checkjni=0 \
  ro.disable.xlog=0 \
  persist.sys.usb.config=mtp,adb \
  ro.mount.fs=EXT4 \
  camera.disable_zsl_mode=1 \
  ro.agui.cts=yes \
  ro.fingerprint.keep_fingers=yes \
  ro.gqp15.cts.kernel.version=yes \
  ro.agui.tee.test=yes \
  ro.testmode.code_for_tee=yes \
  ro.default_battery_percentage=yes \
  persist.radio.multisim.config=dsds \
  net.bt.name=d0ndroid \
  ro.mtk.trustkernel_tee_support=1 \
  ro.agui.cts=yes \
  ro.fingerprint.keep_fingers=yes \
  ro.gqp15.cts.kernel.version=yes \
  ro.agui.tee.test=yes \
  ro.testmode.code_for_tee=yes \
  ro.smartpa.calib=yes \
  ro.agui_fingerprint.function=yes \
  ro.agui.fingerprint_back=no \
  ro.agui.fingerprint_home=no \
  ro.agui.findsensor=front \
  ro.agui_double_tap_power_cam=yes \
  ro.default_battery_percentage=no \
  ro.CALENDAR_VALUE_TYPE=4 \
  ro.agui.hide.draintime=yes \
  ro.agui.eng_mode_show_dialog=no \
  ro.agui.remove.baseversion=yes \
  ro.testmode.code_for_gq=yes \
  ro.agui.appname.mult=yes \
  ro.restart.summary=yes \
  ro.REMOVE_HALL_TEST=yes \
  ro.agui.remove.eye_protect=yes \
  ro.battery_charging_led=yes \
  ro.miss_call_ledcolor=Green \
  ro.other_notifi_ledcolor=Green \
  ro.unread_notifi_ledcolor=Green \
  ro.incoming_ledcolor=Green \
  ro.scridle_ledcolor=None \
  ro.agui.tpd.add.gesture=yes \
  ro.agui.system.gesture=yes \
  ro.agui.led.nomed=yes \
  ro.agui.colorful.led=None,Red,Green,Blue \
  ro.low_battery_led=yes \
  ro.navigationbar.add_hide=yes \
  ro.kwu1.setting=2 \
  ro.agui.nav_hide_btn=false \
  ro.agui.nav_home_long_recent=yes \
  ro.kwu1.nav_or_realbtn=virtual \
  ro.nav.gq=yes \
  ro.cts_mode=yes \
  ro.fingerprint.support=SUNWAVE_TRUSTKERNEL \
  ro.config.nav_bar_show=yes \
  ro.config.notification_sound=TaDa.ogg \
  ro.config.mms_sound=TaDa.ogg \
  ro.config.alarm_alert=Alarm_Classic.ogg \
  ro.config.ringtone=ANDROMEDA.ogg \
  ro.def.volume.music=11 \
  ro.def.volume.ring=11 \
  ro.def.volume.voice.calll=6 \
  ro.def.volume.system=11 \
  ro.def.volume.alarm=11 \
  ro.def.volume.notification=11 \
  ro.def.volume.dtmf=6 \
  ro.def.volume.system.enforced=6 \
  ro.def.volume.bluetooth.sco=6 \
  ro.def.volume.volume.tts=6 \
  ro.nor.key.vol=108,132,156,180,204,228,252 \
  ro.hed.key.vol=108,132,156,180,204,228,252 \
  ro.hnd.key.vol=108,132,156,180,204,228,252 \
  ro.hnd.ring.vol=unknown \
  ro.hed.ring.vol=unknown \
  ro.dialpad.tone.volume=80 \
  ro.def.camera.flash=off \
  ro.def.camera.flash.main=auto \
  ro.def.camera.flash.sub=off \
  ro.agui.remove.wallpaper.menu=yes \
  ro.agui.add.contact.count=yes \
  ro.agui.add.eyeprotect=no \
  ro.shortcut_flashlight=no \
  ro.agui.kg_longhome_fl_useable=no \
  ro.def.camera.zsd=on \
  ro.def.camera.face=off \
  ro.def.camera.ais=off \
  ro.def.camera.video.quality=110 \
  ro.launcher.packagename=AGOLD_EMPTY \
  ro.launcher.activityname=AGOLD_EMPTY \
  ro.def.camera.pic.size.main=4672x3504 \
  ro.def.camera.pic.size.sub=4160x3120 \
  ro.def.camera.exposure.main=0 \
  ro.def.camera.exposure.sub=0 \
  ro.def.camera.antiband.main=auto \
  ro.def.camera.antiband.sub=auto \
  ro.def.camera.bright.main=middle \
  ro.def.camera.bright.sub=middle \
  ro.gprs.switch=no \
  ro.keyboard.vibrate.value=0 \
  ro.build.shutdown.animation=no \
  ro.build.time.format=24 \
  ro.build.date.format=yyyy-MM-dd \
  ro.auto.time.update=yes \
  ro.auto.timezone.update=no \
  ro.build.default.scrbrightness=153 \
  ro.build.max.scrbrightness=255 \
  ro.install.nonmarket.switch=no \
  ro.gravity.rotation=yes \
  ro.screenoff.timout=30000 \
  ro.closescreen.timeout=6000 \
  ro.build.ipo.setting=yes \
  ro.alarm.snooze.time=5 \
  ro.alarm.silence.time=5 \
  ro.wifi.notification=no \
  ro.wifi.sleepmode=2 \
  ro.powerkey.function=0 \
  ro.install.location=0 \
  ro.build.staticwp=com.agold.launcher.wallpaper/wallpaper_11 \
  ro.build.lockwallpaper=com.agold.launcher.wallpaper/wallpaper_11 \
  ro.build.lockwpfunc=yes \
  ro.audioprofile_general_vibrate=no \
  ro.build.keyboard.touchaudio=yes \
  ro.build.touch.sound=no \
  ro.lockscreen.sound=yes \
  ro.touch.vibrator.feed=yes \
  ro.audioprofile.more=no \
  or.build.vibratorvol=0 \
  or.build.vibratortime=0 \
  or.button.ledvalue=-1 \
  ro.browser.homepage=http://ulefone.com \
  ro.nosignal.hideicons=yes \
  ro.show.navigationbar=yes \
  ro.phone.min.num.match=7 \
  ro.build.autobrightness=no \
  ro.roaming.reminder=-1 \
  ro.wifimac.tonvram=1 \
  ro.acc.alps.calibration=acc,alps \
  ro.transition.animation=1 \
  ro.build.fontsize=AGOLD_EMPTY \
  ro.sf.lcd_density=480 \
  ro.def.camera.zsd.main=AGOLD_EMPTY \
  ro.def.camera.zsd.sub=AGOLD_EMPTY \
  ro.enable.internet.call=no \
  ro.sip.receiver.call=no \
  ro.gallery.scale.image=0.76 \
  ro.remove.wifi.display=yes \
  ro.agui.keymap=VOLUMEUP,VOLUMEDOWN \
  ro.signal.4g=-135,-130,-120,-105 \
  ro.signal.2g=-109,-103,-97,-89 \
  ro.signal.3g=-110,-105,-100,-95 \
  ro.ag.userswitch=no \
  ro.default.gps.switch=gps,network \
  ro.def.remove.screen.pining=0 \
  ro.cloud.settings.ui=0 \
  ro.locale_update_first_sim=yes \
  ro.turn.silent.settings=false \
  ro.short.cut.settings=false \
  ro.app.short.cut=Settings \
  ro.swich.short.cut.settings=false \
  ro.one.key.sos.mode=0 \
  ro.sdcard_support=yes \
  ro.camera.longpress_start=yes \
  ro.keytest_func_name=FUNC1,FUNC2 \
  ro.kw.storage.ui=0 \
  ro.agui.datausage.enable=no \
  ro.remove.displaysize=yes \
  ro.show.more.ringtone=1 \
  ro.support.screen.record=yes \
  ro.agui.remove.bg_task_clear=yes \
  ro.bg.task.clear=0 \
  ro.def.touch.photo=on \
  ro.com.google.clientidbase=android-agold \
  ro.agui.accident=no \
  ro.agui.customversion.remove=yes \
  ro.remove.multiuser.switch=no \
  ro.touch.sound=no \
  ro.dial_on_resume=yes \
  ro.agui.changelable=yes \
  ro.agui_default_storage_sd=yes \
  ro.vibrate_when_ringing=yes \
  ro.agui.non_touch_operation=no \
  ro.agui.one_hand_mode=no \
  ro.agui.add.focus.sound=yes \
  ro.SUB_FLASHLIGHT=yes \
  ro.remove.suggestions=yes \
  ro.translate.language=yes \
  ro.remove.rotation=yes \
  ro.lock.qs.enabled=yes \
  ro.agui.rm_live_in_bokeh=no \
  ro.agui.camera_live_photo=no \
  ro.default.usb_charging=yes \
  ro.fastpass.gms_support=yes \
  ro.setupwizard.mode=OPTIONAL \
  ro.com.google.gmsversion=7.0_r9 \
  ro.mediatek.chip_ver=S01 \
  ro.mediatek.platform=MT6757 \
  ro.telephony.sim.count=2 \
  persist.radio.default.sim=0 \
  ril.specific.sm_cause=0 \
  bgw.current3gband=0 \
  ril.external.md=0 \
  ro.mtk_cam_lomo_support=1 \
  ro.sf.hwrotation=180 \
  persist.radio.fd.counter=150 \
  persist.radio.fd.off.counter=50 \
  persist.radio.fd.r8.counter=150 \
  persist.radio.fd.off.r8.counter=50 \
  drm.service.enabled=true \
  fmradio.driver.enable=1 \
  mtk.eccci.c2k=enabled \
  ril.first.md=1 \
  ril.flightmode.poweroffMD=1 \
  ril.telephony.mode=0 \
  dalvik.vm.mtk-stack-trace-file=/data/anr/mtk_traces.txt \
  mediatek.wlan.chip=CONSYS_MT6757 \
  mediatek.wlan.module.postfix=_consys_mt6757 \
  ril.read.imsi=1 \
  ril.radiooff.poweroffMD=0 \
  ro.frp.pst=/dev/block/platform/mtk-msdc.0/11230000.msdc0/by-name/frp \
  ro.mtk_protocol1_rat_config=C/Lf/Lt/W/G \
  ro.mediatek.version.branch=alps-mp-n0.mp5 \
  ro.mediatek.version.release=alps-mp-n0.mp5-V1.19_even6757.66.n_P33 \
  ro.mediatek.version.sdk=4 \
  ro.num_md_protocol=2 \
  persist.radio.multisim.config=dsds \
  ro.mtk_besloudness_support=1 \
  ro.mtk_wapi_support=1 \
  ro.mtk_bt_support=1 \
  ro.mtk_wappush_support=1 \
  ro.mtk_agps_app=1 \
  ro.mtk_audio_tuning_tool_ver=V2.2 \
  ro.mtk_wlan_support=1 \
  ro.mtk_gps_support=1 \
  ro.mtk_omacp_support=1 \
  ro.mtk_search_db_support=1 \
  ro.mtk_dialer_search_support=1 \
  ro.mtk_dhcpv6c_wifi=1 \
  ro.have_aacencode_feature=1 \
  ro.mtk_fd_support=1 \
  ro.mtk_oma_drm_support=1 \
  ro.mtk_cta_drm_support=1 \
  ro.mtk_widevine_drm_l3_support=1 \
  ro.mtk_eap_sim_aka=1 \
  ro.mtk_send_rr_support=1 \
  ro.mtk_emmc_support=1 \
  ro.mtk_tetheringipv6_support=1 \
  ro.mtk_c2k_support=1 \
  persist.radio.flashless.fsm=0 \
  persist.radio.flashless.fsm_cst=0 \
  persist.radio.flashless.fsm_rw=0 \
  ro.cdma.cfu.enable=*72 \
  ro.cdma.cfu.disable=*720 \
  ro.cdma.cfb.enable=*90 \
  ro.cdma.cfb.disable=*900 \
  ro.cdma.cfnr.enable=*92 \
  ro.cdma.cfnr.disable=*920 \
  ro.cdma.cfdf.enable=*68 \
  ro.cdma.cfdf.disable=*680 \
  ro.cdma.cfall.disable=*730 \
  ro.cdma.cw.enable=*74 \
  ro.cdma.cw.disable=*740 \
  telephony.lteOnCdmaDevice=1 \
  ro.telephony.default_network=10,10 \
  ro.mtk_shared_sdcard=1 \
  ro.mtk_enable_md1=1 \
  ro.mtk_enable_md3=1 \
  ro.mtk_afw_support=1 \
  ro.mtk_flight_mode_power_off_md=1 \
  ro.mtk_aal_support=1 \
  ro.mtk_pq_support=1 \
  ro.mtk_pq_color_mode=1 \
  ro.mtk_miravision_support=1 \
  ro.mtk_blulight_def_support=1 \
  ro.mtk_wfd_support=1 \
  ro.mtk_wfd_sink_support=1 \
  ro.mtk_wfd_sink_uibc_support=1 \
  ro.mtk_wifi_mcc_support=1 \
  ro.mtk_sim_hot_swap=1 \
  ro.mtk_bip_scws=1 \
  ro.mtk_world_phone_policy=0 \
  ro.mtk_md_world_mode_support=1 \
  ro.mtk_perfservice_support=1 \
  ro.mtk_sim_hot_swap_common_slot=1 \
  ro.mtk_cta_set=1 \
  ro.mtk_zsdhdr_support=1 \
  ro.mtk_cam_mfb_support=3 \
  ro.mtk_slow_motion_support=1 \
  ro.mtk_lte_support=1 \
  ro.mtk_rild_read_imsi=1 \
  ro.sim_refresh_reset_by_modem=1 \
  ro.mtk_external_sim_only_slots=0 \
  ro.mtk_bg_power_saving_support=1 \
  ro.mtk_bg_power_saving_ui=1 \
  ro.sim_me_lock_mode=0 \
  ro.mtk_dual_mic_support=1 \
  ro.mtk_is_tablet=0 \
  ro.mtk_pow_perf_support=1 \
  persist.mtk_nlp_switch_support=1 \
  persist.mtk_ims_support=1 \
  ro.mtk_multiple_ims_support=1 \
  persist.mtk_volte_support=1 \
  persist.mtk.volte.enable=0 \
  persist.mtk_vilte_support=1 \
  ro.mtk_vilte_ut_support=0 \
  wfd.dummy.enable=1 \
  wfd.iframesize.level=0 \
  ro.mediatek.project.path=device/ulefone/t1 \
  persist.mtk.wcn.combo.chipid=-1 \
  persist.mtk.wcn.patch.version=-1 \
  persist.mtk.wcn.dynamic.dump=0 \
  service.wcn.driver.ready=no \
  service.wcn.coredump.mode=0 \
  persist.mtk.connsys.poweron.ctl=0 \
  persist.mtk_epdg_support=1 \
  ro.com.android.mobiledata=no \
  persist.radio.mobile.data=0,0 \
  persist.meta.dumpdata=0 \
  ro.mtk_deinterlace_support=1 \
  ro.telephony.ril.config=fakeiccid \
  dalvik.vm.usejit=true \
  dalvik.vm.usejitprofiles=true \
  dalvik.vm.appimageformat=lz4 \
  ro.mount.fs=EXT4 \
  camera.disable_zsl_mode=1 \
  ro.dalvik.vm.native.bridge=0

