#!/bin/bash

VENDOR=ulefone
DEVICE=t1
OUTDIR=${bdir}/vendor/$VENDOR/$DEVICE
AMAKE=${OUTDIR}/Android.mk
BMAKE=${OUTDIR}/$DEVICE-vendor-blobs.mk
VMAKE=${OUTDIR}/$DEVICE-vendor.mk

echo "# Copyright (C) 2015 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/$VENDOR/$DEVICE/setup-makefiles.sh

PRODUCT_COPY_FILES += \\" >$BMAKE

echo "# Copyright \(C\) 2015 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an \"AS IS\" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/$VENDOR/$DEVICE/setup-makefiles.sh

\$(call inherit-product, vendor/$VENDOR/$DEVICE/$DEVICE-vendor-blobs.mk)
" >$VMAKE

cd $OUTDIR/proprietary >/dev/null
declare -a FILES
FNS=$(find * -xtype f -not -name *.odex -and -not -name *.apk |wc -l)
CNT=0
for I in $(find * -xtype f -not -name *.odex -and -not -name *.apk) ;do
  let CNT+=1
  LEND=' \\'
  if [ "$FNS" == "$CNT" ] ;then
    LEND=''
  fi
  if [ "$(basename $I)" == "libGLES_mali.so" ] ;then
    LEND=":linaro$LEND"
  fi
  #grep -qs "$I" $AMAKE && continue
  printf "  vendor/$VENDOR/$DEVICE/proprietary/${I}:system/${I}${LEND}\n" >> $BMAKE
done
cd - >/dev/null
