#!/bin/bash

VENDOR=ulefone
DEVICE=t1
OUTDIR=${BDIR}/vendor/$VENDOR/$DEVICE
AMAKE=${OUTDIR}/Android.mk
BMAKE=${OUTDIR}/$DEVICE-vendor-blobs.mk
VMAKE=${OUTDIR}/$DEVICE-vendor.mk


echo "# Copyright (C) 2015 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/$VENDOR/$DEVICE/setup-makefiles.sh

PRODUCT_COPY_FILES += \\" >$BMAKE

echo "# Copyright \(C\) 2015 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an \"AS IS\" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/$VENDOR/$DEVICE/setup-makefiles.sh

\$(call inherit-product, vendor/$VENDOR/$DEVICE/$DEVICE-vendor-blobs.mk)
" >$VMAKE

echo "# Copyright (C) 2015 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/$VENDOR/$DEVICE/setup-makefiles.sh

LOCAL_PATH := \$(call my-dir)
" >$AMAKE

cd $OUTDIR/proprietary >/dev/null
declare -a FILES
FNS=$(find * -type f |wc -l)
CNT=0
for I in $(find * -type f) ;do
  let CNT+=1
  LEND=' \\'
  if [ "$FNS" == "$CNT" ] ;then
    LEND=''
  fi
  if [ "$(echo $I |awk -F'.' '{print $NF}')" == "apk" ] ;then
    APKDIR=$(echo $I |awk -F '/' '{print $2}')
    printf "\ninclude \$(CLEAR_VARS)\nLOCAL_MODULE := $(basename $I |sed 's/\.apk//')\nLOCAL_SRC_FILES := proprietary/${I}\nLOCAL_MODULE_SUFFIX := .apk\nLOCAL_MODULE_CLASS := APPS\nLOCAL_CERTIFICATE := PRESIGNED\nLOCAL_MODULE_PATH := \$(TARGET_OUT)/${APKDIR}\ninclude \$(BUILD_PREBUILT)\n" >> $AMAKE
  else
    printf "  ${OUTDIR}/proprietary/${I}:${I}${LEND}\n" >> $BMAKE
  fi
done
cd - >/dev/null
