#!/bin/bash

VENDOR=ulefone
DEVICE=t1
OUTDIR=${bdir}/vendor/$VENDOR/$DEVICE
AMAKE=${OUTDIR}/Android.mk
CMAKE=${OUTDIR}/VendorBoardConfig.mk
BMAKE=${OUTDIR}/t1-vendor-blobs.mk

#echo "# Copyright (C) 2015 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/$VENDOR/$DEVICE/setup-makefiles.sh

#PRODUCT_PACKAGES += \\" >$CMAKE

#echo "# Copyright (C) 2015 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/$VENDOR/$DEVICE/setup-makefiles.sh

#LOCAL_PATH := \$(call my-dir)
#" >$AMAKE

cd $OUTDIR/proprietary >/dev/null
for I in $(find * -type f -name *.so) ;do
  LIB=$(basename $I)
  DDIR=$(dirname $I)
  LLDIR=$(echo $DDIR |sed -r 's/.*lib6?4?(.*)/\1\//' |sed -r 's/^\///')
  LDDIR=$(echo $DDIR |sed -r 's/(.*)lib6?4?.*/\1/' |sed -r 's/^\///')
  grep -qs $I $BMAKE && continue
  grep -qs $I $AMAKE && continue
  grep -qs $LIB $ddir/blacklibs.lst && continue
  L32="${LDDIR}lib/${LLDIR}${LIB}"
  L64="${LDDIR}lib64/${LLDIR}${LIB}"
  printf "include \$(CLEAR_VARS)\nLOCAL_MODULE_CLASS := SHARED_LIBRARIES\n" >> $AMAKE
  [ "$LDDIR" == "vendor/" ] && printf "LOCAL_PROPRIETARY_MODULE := true\n" >> $AMAKE
  printf "LOCAL_ALLOW_UNDEFINED_SYMBOLS := true\n" >> $AMAKE
  if [ -f "${L32}" -a -f "${L64}" ] ;then
    printf "LOCAL_MULTILIB := both\nLOCAL_MODULE := ${LIB%.*}\nLOCAL_SRC_FILES_32 := proprietary/${L32}\nLOCAL_SRC_FILES_64 := proprietary/${L64}\n" >> $AMAKE
  elif [ -f "${L32}" ] ;then
    printf "LOCAL_MULTILIB := 32\nLOCAL_MODULE := ${LIB%.*}\nLOCAL_SRC_FILES_32 := proprietary/${L32}\n" >> $AMAKE
  elif [ -f "${L64}" ] ;then
    printf "LOCAL_MULTILIB := 64\nLOCAL_MODULE := ${LIB%.*}\nLOCAL_SRC_FILES_64 := proprietary/${L64}\n" >> $AMAKE
  else
    echo "\033[31mERROR: $I\033[0m"
  fi
  [[ $LLDIR ]] && printf "LOCAL_MODULE_PATH := \$(TARGET_OUT_SHARED_LIBRARIES)/$(echo $LLDIR |sed 's/\/$//')\n" >>$AMAKE
  if [ "$LIB" == "libRSDriver_mtk.so" ] || [ "$LIB" == "libRSDriverArm.so" ] || [ "$LIB" == "libOpenCLIcd.so" ] || [ "$LIB" == "libOpenCL.so" ] ;then
    printf "LOCAL_SHARED_LIBRARIES = libc++ libz libutils libRS_internal libbcinfo liblog libEGL libGLESv1_CM libGLESv2 libnativewindow\n" >> $AMAKE
  fi
  printf "LOCAL_MODULE_SUFFIX := .so\ninclude \$(PREBUILT_SHARED_LIBRARY)\n\n" >> $AMAKE
  printf "  ${LIB%.*}" >> $CMAKE
  echo ' \' >> $CMAKE
done
cd - >/dev/null
